name: release
on:
  push:
    tags:
      - "*"
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: echo "implement e2e tests"
  merge:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.AGENCY_RELEASER_ID }}
          private-key: ${{ secrets.AGENCY_RELEASER_KEY }}
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ steps.generate_token.outputs.token }}
      - name: merge
        run: |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master
