name: test
on: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install indy
        run: make indy_to_debian
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
  test:
    runs-on: ubuntu-latest
    steps:
      # setup indy ledger
      - uses: actions/checkout@v2
        with:
          repository: "bcgov/von-network"
      - name: start indy ledger
        run: ./manage build && ./manage start

      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: install indy
        run: make indy_to_debian

      # test with internal ledger
      - name: test and measure coverage
        run: make test_cov_out COV_FILE=coverage1.txt

      # test with indy ledger
      - name: test and measure coverage
        run: make test_cov_out COV_FILE=coverage2.txt
        env:
          FINDY_POOL: "FINDY_LEDGER,test"
      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage1.txt, ./coverage2.txt
