name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: optechlab/indy-golang:1.16.0
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: make test